# Generated by Django 5.2.9 on 2025-12-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_iso', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['codigo_iso'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('monto_divisa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cotizacion', models.DecimalField(decimal_places=4, help_text='Cotización de la divisa expresada en ARS.', max_digits=15)),
                ('total_ars', models.DecimalField(decimal_places=2, help_text='monto_divisa * cotizacion. Se calcula automáticamente.', max_digits=18)),
                ('fuente', models.CharField(blank=True, help_text='Origen del movimiento: Liu, cliente, caja, etc.', max_length=50)),
                ('notas', models.TextField(blank=True, help_text='Campo libre para observaciones.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='exchange.moneda')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
