# Generated by Django 4.2.27 on 2026-01-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_initial_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='total_ars',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='monto_divisa * cotizacion. Se calcula automáticamente.', max_digits=18, null=True),
        ),
    ]
